### ISSUE TITLE
understanding of thermo functions within pyemma

### ISSUE THREAD

**Issue by liyigerry** [jmelcr/eGFP-scripts#1]
Hi, Josef Melcr,

I find your [script](https://github.com/jmelcr/eGFP-scripts/blob/master/pyEMMA-TRAM_analyze.py), but I can not understand about ttrajs and dtrajs generated from metadynamics with plumed.

How can I extract ttrajs and dtrajs from the COLVAR or HILLS generated by plumed?

There are four methods, tram, dtram, wham and mbar. How can I choose them?

Waiting for your help. Thanks.

Li Yi

**Comment by jmelcr** [comment]
Hello Li,
I'm unsure of what is your intention with the particular script -- it says in the very beginning that it serves a very particular pupose and might not suit anything else.
I did some tests with metadynamics simulations and dTRAM, but it is not simply applicable to this script. 
Can you be more specific?

**Comment by jmelcr** [comment]
I'm closing this issue, as it is not active.
